### ISSUE TITLE
Update docker-compose container db comment to acknowledge n+1 groundswell activation

### ISSUE THREAD

**Issue by gwright99** [seqeralabs/docs#43]
Existing [docker-compose.yml](https://docs.seqera.io/assets/files/docker-compose-d00e0de8ffaf5450e7181a8f097da3f9.yml) has the following comment re: container db & `groundswell`:

```yaml
version: "3"
services:
  db:
    image: mysql:8.0
    platform: linux/amd64
    networks:
      - backend
    expose:
      - 3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_USER: tower
      MYSQL_PASSWORD: tower
      MYSQL_DATABASE: tower
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
    restart: always
    volumes:
      #  To use the pipeline resource optimization service, uncomment the lines below to mount the initialization script
      #  - type: bind
      #    source: ./init.sql
      #    target: /docker-entrypoint-initdb.d/init.sql

      # Store the MySQL data in a directory on the host
      - $HOME/.tower/db/mysql:/var/lib/mysql
```

Uncommenting the `init.sql` block [won't actually work if the data directory already exists](https://github.com/seqeralabs/nf-tower-docs/issues/585#:~:text=1a.%20If%20the,1017742%0AFLUSH%20PRIVILEGES%3B). 

Guidance should be added to the groundswell comment that post-deployment activation of groundswell requires manual intervention by the system maintainer.
