### ISSUE TITLE
"Create a persistent API token for the tower-launcher-sa service account:"

### ISSUE THREAD

**Issue by PeterKneale** [seqeralabs/docs#630]
hi,

I'm following the k8s installation docs here: https://docs.seqera.io/platform-cloud/compute-envs/k8s
There is a step describing the process of creating a persistant api token.

```yaml
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: tower-launcher-token
  annotations:
    kubernetes.io/service-account.name: tower-launcher-sa
type: kubernetes.io/service-account-token
EOF
```

These long lived tokens no longer appear to be recommend and are described as 'legacy tokens' and the yaml above does not appear to even generate a secret any more. I believe tokens are now cycled periodically, expired if unused and their lifecycle is somewhat different too.

Are there updated instructions available for k8s v1.32?

Thanks!

**Comment by gavinelder** [comment]
Hi @PeterKneale apologies for the delay in response on this issue. 

For Kubernetes it should still be possible to generate a long lived token however this may depend on your specific cluster configuration. 

```
kubectl apply -f - <<EOF
apiVersion: v1
kind: Secret
metadata:
  name: tower-launcher-token
  namespace: tower-nf
  annotations:
    kubernetes.io/service-account.name: tower-launcher-sa
type: kubernetes.io/service-account-token
EOF
```

The token should be found at `kubectl get secret tower-launcher-token -n tower-nf -o jsonpath='{.data.token}' | base64 -d` 

However Kubernetes now supports the [create token](https://kubernetes.io/docs/reference/kubectl/generated/kubectl_create/kubectl_create_token/) command which allows you to generate a token with a set lifecycle. 

`kubectl create token tower-launcher-sa --duration=8760h --namespace=tower-nf` 

We are currently reworking a number of these installation documentation items. 

Further to that kubernetes now time-bound tokens generated via the TokenRequest API  which we may be able to implement.
